config/routes.rb
Rails.application.routes.draw do
  get 'users/new' => 'users#new'
  get 'users/show' => 'users#show'
  get 'comments/create' => 'comments#create'
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :meals do
    resources :likes, only: [:create, :destroy]
    resource :comments, only: [:create]
    collection do
      get 'search'
    end
  end
  resources :comments, only: [:destroy]
  root 'meals#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :meal
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :meal
  belongs_to :user
  validates_uniqueness_of :meal_id, scope: :user_id
end

app/models/meal.rb
class Meal < ApplicationRecord
    belongs_to :user, optional: true
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :meals, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_meals, through: :likes, source: :meal
  validates :name, presence: true
  validates :profile, length: {maximum: 200}

  mount_uploader :avatar, AvatarUploader

  def already_liked?(meal)
    self.likes.exists?(meal_id: meal.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :avatar])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    meal = Meal.find(params[:meal_id])
    comment = meal.comments.build(comment_params) #buildを使い、contentとmeal_idの二つを同時に代入
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "メモしました"
      redirect_back(fallback_location: :root_path)
    else
      flash[:success] = "メモできませんでした"
      redirect_back(fallback_location: :root_path)
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_back(fallback_location: :root_path)
  end
  
  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(meal_id: params[:meal_id]) #user_idとmeal_idの二つを代入
        redirect_back(fallback_location: :root_path)
      end
    
      def destroy
        like = Like.find_by(meal_id: params[:meal_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: :root_path)
      end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_q, only: [:index, :search]

  def index
    @meals = Meal.all.order("id DESC")
    @meals_like = Meal.limit(10).includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
  end

  def new
    @meal = Meal.new
  end

  def show
    @meal = Meal.find(params[:id])
    @comments = @meal.comments
    @comment = Comment.new
  end

  def edit
    @meal = Meal.find(params[:id])
  end

  def create
    meal = Meal.new(meals_params)
    meal.user_id = current_user.id
    if meal.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def update
    meal = Meal.find(params[:id])
    if meal.update(meals_params)
      redirect_to :action => "show", :id => meal.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    meal = Meal.find(params[:id])
    meal.destroy
    redirect_to action: :index
  end
  
  def search
    @results = @q.result.sort {|a,b| b.liked_users.size <=> a.liked_users.size}
  end

  private
  
  def set_q
    @q = Meal.ransack(params[:q])
  end
  
  def meals_params
    params.require(:meal).permit(:name, :image, :feeling, :ingredient, :time, :kinds, :dish)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :profile, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>献立る</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <h1>献立る</h1>
    <div class="header-list">
      <ul>
        <%= link_to meals_path do %>
          <span>ホーム</span>
          <li><i class="fas fa-home fa-lg"></i></li>
        <% end %>
        <% if user_signed_in? %>
          <%= link_to user_path(current_user.id) do %>
            <span>マイページ</span>
            <li><i class="fas fa-smile fa-lg"></i></li>
          <% end %>
        <% else %>
          <%= link_to new_user_session_path do%>
            <span>ログイン</span>
            <li><i class="fas fa-sign-in-alt fa-lg"></i></li>
          <% end %>
        <% end %>
      </ul>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
    <div class="top-btn">
      <a href="#">
      <i class="fas fa-chevron-circle-up fa-lg"></i>
      </a>
    </div>
    <div class="under-menu-box">
      <ul>
        <% if user_signed_in? %>
          <li><a href="/meals/new"><p><i class="fas fa-search-plus fa-lg"></i></p>
          <span>献立を増やす</span></a></li>
        <% else %>
          <li><a href="/users/sign_in"><p><i class="fas fa-search-plus fa-lg"></i></p>
          <span>献立を増やす</span></a></li>
        <% end %>
        <li><a href="/meals#ranking"><p><i class="fas fa-fire-alt fa-lg"></i></p>
        <span>人気の献立</span></a></li>
        <li><a href="/meals#recent"><p><i class="fas fa-thumbtack fa-lg"></i></p>
        <span>最近の献立</span></a></li>
      </ul>
    </div>
    <footer>
      <p>Copyright ©️ GeekSalon All Rights Reserved.</p>
    </footer>
  </body>
</html>

app/views/meals/create.html.erb
<h1>Meals#create</h1>
<p>Find me in app/views/meals/create.html.erb</p>

app/views/meals/edit.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>献立る</title>
    <link rel="stylesheet" type="text/css" href="stylesheets/edit.scss">
  </head>
<div class="meal-edit">
<h3>編集ページ</h3>
<%= form_for @meal do |f| %>
    <%= f.label :料理名 %>
    <%= f.text_field :name, :size => 140 %> 
    <br>
    <%= f.label :写真 %>
    <%= f.file_field :image %>
    <br>
    <h4>どんな時に食べる？</h4>
    <%= f.radio_button :feeling, '', {:checked => true} %>指定なし
    <%= f.radio_button :feeling, :ガッツリ %>ガッツリ
    <%= f.radio_button :feeling, :あっさり %>あっさり
    <%= f.radio_button :feeling, :くつろぐ %>くつろぐ
    <%= f.radio_button :feeling, :あたたまる %>あたたまる
    <br>
    <h4>主に使う食材は？</h4>
    <%= f.radio_button :ingredient, '', {:checked => true} %>指定なし
    <%= f.radio_button :ingredient, :肉 %>肉
    <%= f.radio_button :ingredient, :魚 %>魚
    <%= f.radio_button :ingredient, :野菜 %>野菜
    <%= f.radio_button :ingredient, :卵 %>卵
    <h4>いつ食べる？</h4>
    <%= f.radio_button :time, '', {:checked => true} %>指定なし
    <%= f.radio_button :time, :朝 %>朝
    <%= f.radio_button :time, :昼 %>昼
    <%= f.radio_button :time, :夜 %>夜
    <%= f.radio_button :time, :いつでも %>いつでも
    <h4>ジャンルは？</h4>
    <%= f.radio_button :kinds, '', {:checked => true} %>指定なし
    <%= f.radio_button :kinds, :和 %>和
    <%= f.radio_button :kinds, :洋 %>洋
    <%= f.radio_button :kinds, :中 %>中
    <h4>ポジションは？</h4>
    <%= f.radio_button :dish, '', {:checked => true} %>指定なし
    <%= f.radio_button :dish, :主菜 %>主菜
    <%= f.radio_button :dish, :副菜 %>副菜
    <%= f.radio_button :dish, :汁物 %>汁物
    <%= f.radio_button :dish, :主食 %>主食
    <br>
    <%= f.submit "編集する" %>
  <% end %>
  </div>
  </html>

app/views/meals/search.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>献立る</title>
    <link rel="stylesheet" type="text/css" href="stylesheets/search.scss">
  </head>
<body>
<div class="search-meals">
  <h3>おすすめの献立</h3>
  <div class="condition">
  <h4>検索条件</h4>
    <div class="meal-detail">
      <div class="detail-title">
        <p><i class="far fa-comment-dots"></i> 気分</p>
        <p><i class="fas fa-seedling"></i> 食材</p>
        <p><i class="far fa-clock"></i> 時間帯</p>
        <p><i class="far fa-calendar-minus"></i> ジャンル</p>
        <p><i class="fas fa-utensils"></i> ポジション</p>
      </div>
      <div class="detail-content">
        <p><%= params[:q][:feeling_eq] unless params[:q][:feeling_eq].empty? %><%= '指定なし' if params[:q][:feeling_eq].empty? %></p>
        <p><%= params[:q][:ingredient_eq] unless params[:q][:ingredient_eq].empty? %><%= '指定なし' if params[:q][:ingredient_eq].empty? %></p>
        <p><%= params[:q][:time_eq] unless params[:q][:time_eq].empty? %><%= '指定なし' if params[:q][:time_eq].empty? %></p>
        <p><%= params[:q][:kinds_eq] unless params[:q][:kinds_eq].empty? %><%= '指定なし' if params[:q][:kinds_eq].empty? %></p>
        <p><%= params[:q][:dish_eq] unless params[:q][:dish_eq].empty? %><%= '指定なし' if params[:q][:dish_eq].empty? %></p>
      </div>
    </div>
    <% unless @results.first %>
    <%= image_tag ("sorry.png"), width: '80%', height: '60%' %>
    <p>条件に合う献立を見つけられませんでした</p>
    <% if user_signed_in? %>
      <p><%= link_to '献立を増やす', new_meal_path %></p>
    <% else %>
      <p><%= link_to '献立を増やす', user_session_path %></p>
    <% end %>
  <% end %>
  <%= link_to "検索条件を変える", meals_path %>
  </div>
  <% @results.each do |meal| %>
    <div class="meals-container">
    <div class="meal">
      <p class="mealname"><%= meal.name %></p>
      <% if meal.image? %>
          <%= image_tag meal.image_url, size: "250x200" %>
      <% else %>
          <%= image_tag ("no_image.png"), size: "250x200" %>
      <% end %>
      <p class="time">
      <p>作成日: <%= meal.created_at.to_s(:datetime_jp) %></p>
      <p>更新日: <%= meal.updated_at.to_s(:datetime_jp) %></p>
      </p>
      <a class="link" href="/meals/<%= meal.id %>">
      <div class="mask">
        <div class="caption">
          <%= image_tag ("to_show.png"),  width: '100%', height: '100%' %>
        </div>
      </div>
      </a>
    </div>
    <div class="like">
    <% if user_signed_in? %>
      <% if current_user.already_liked?(meal) %>
        <%= link_to meal_like_path(id: meal.id, meal_id: meal.id), method: :delete do %>
          <i class="fas fa-heart fa-lg"></i><%= meal.likes.count %>
        <% end %>
      <% else %>
        <%= link_to meal_likes_path(id: meal.id, meal_id: meal.id), method: :post do %>
          <i class="far fa-heart fa-lg"></i><%= meal.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <i class="far fa-heart fa-lg"></i><%= meal.likes.count %>
    <% end %>
    </div>
    </div>
  <% end %>
</div>
</body>
</html>

app/views/meals/show.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>献立る</title>
    <link rel="stylesheet" type="text/css" href="stylesheets/show.scss">
  </head>
<div class="meal-show">
<div class="meal">
  <p class="mealname"><%= @meal.name %></p>
  <% if @meal.image? %>
      <%= image_tag @meal.image_url, size: "250x200" %>
  <% else %>
      <%= image_tag ("no_image.png"), size: "250x200" %>
  <% end %>
  <div class="meal-detail">
    <div class="detail-title">
      <p><i class="far fa-comment-dots"></i> 気分</p>
      <p><i class="fas fa-seedling"></i> 食材</p>
      <p><i class="far fa-clock"></i> 時間帯</p>
      <p><i class="far fa-calendar-minus"></i> ジャンル</p>
      <p><i class="fas fa-utensils"></i> ポジション</p>
    </div>
    <div class="detail-content">
      <p><%= @meal.feeling if @meal.feeling? %><%= '指定なし' unless @meal.feeling? %></p>
      <p><%= @meal.ingredient if @meal.ingredient?%><%= '指定なし' unless @meal.ingredient? %></p>
      <p><%= @meal.time if @meal.time? %><%= '指定なし' unless @meal.time? %></p>
      <p><%= @meal.kinds if @meal.kinds? %><%= '指定なし' unless @meal.kinds? %></p>
      <p><%= @meal.dish if @meal.dish? %><%= '指定なし' unless @meal.dish? %></p>
    </div>
  </div>
  <div class="like_and_comment">
  <div class="do_like">
  <% if user_signed_in? %>
    <% if current_user.already_liked?(@meal) %>
        <%= link_to meal_like_path(@meal), method: :delete do %>
          <p><i class="fas fa-heart fa-lg"></i><%= @meal.likes.count %></p>
          <p>いいねする</p>
        <% end %>
    <% else %>
        <%= link_to meal_likes_path(@meal), method: :post do %>
          <p><i class="far fa-heart fa-lg"></i><%= @meal.likes.count %></p>
          <p>いいねする</p>
        <% end %>
    <% end %>
  <% else %>
    <%= link_to new_user_session_path do %>
    <p><i class="far fa-heart"></i><%= @meal.likes.count %></p>
    <p>ログインしていいねする</p>
    <% end %>
  <% end %>
  </div>
  <div class="do_comment">
  <% if user_signed_in? %>
    <%= form_with(model: [@meal, @comment], local: true) do |f| %>
      <p><%= f.text_area :content %></p>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% else %>
    <%= link_to new_user_session_path do %>
    <p><i class="far fa-comments"></i></p>
    <p>ログインしてコメントする<p>
    <% end %>
  <% end %>
  </div>
  </div>
  <% if user_signed_in? && current_user.id == @meal.user_id %>
    <%= link_to edit_meal_path(@meal.id) do %>
      <span><i class="fas fa-edit"></i>編集する</span>
    <% end %>
    <%= link_to meal_path(@meal.id), method: :delete, data: {confirm: "削除しますか？"} do %>
      <span><i class="fas fa-trash-alt"></i>削除する</span>
    <% end %>
  <% end %>
  <p class="time">
  <p>作成日: <%= @meal.created_at.to_s(:datetime_jp) %></p>
  <p>更新日: <%= @meal.updated_at.to_s(:datetime_jp) %></p>
  </p>
</div>
<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div class="comment">
      <div class="comment-content">
        <p><%= c.content %><p>
        <p class="time">
          <%= c.created_at.to_s(:datetime_jp) %>
        </p>
        <% if user_signed_in? && current_user.id == c.user_id %>
          <p><%= link_to 'このコメントを削除', comment_path(c.id), data: {confirm: '本当に削除しますか？'}, method: :delete %>
        <% end %>
      </div>
      <div class="comment-user">
        <% if c.user.avatar? %>
          <%= image_tag c.user.avatar_url, class: 'icon' unless c.user.blank? %>
        <% else %>
          <%= image_tag ("knife_and_folk.png"), size: "100x100", class: 'icon' %>
        <% end %>
        <p><h4><%= c.user.name unless c.user.name.blank? %></h4></p>
      </div>
    </div>
  <% end %>
</div>
</div>
</html>

app/views/meals/update.html.erb
<h1>Meals#update</h1>
<p>Find me in app/views/meals/update.html.erb</p>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>献立る</title>
    <link rel="stylesheet" type="text/css" href="stylesheets/new.scss">
  </head>
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>献立る</title>
    <link rel="stylesheet" type="text/css" href="stylesheets/show.scss">
  </head>
  
<body>
<div class="hamburger-menu">
  <input type="checkbox" id="menu-btn-check">
  <label for="menu-btn-check" class="menu-btn"><span></span></label>
  <div class="menu-content">
    <ul>
      <li><a href="#userpost">投稿した料理</a></li>
      <li><a href="#userlike">いいねした料理</a></li>
      <li><a href="#usercomment">コメントした料理</a></li>
    </ul>
  </div>
</div>
<div class="user-profile">
<h2>プロフィール</h2>
<div class="user-white-block">
  <div class="user-logout">
    <span>ログアウト</span>
    <% if current_user.id == @user.id %>
      <%= link_to destroy_user_session_path, method: :delete do %>
        <p><i class="fas fa-sign-out-alt fa-lg"></i></p>
      <% end %>
    <% end %>
  </div>
  <div class="profile-container">
    <div class="user-icon">
    <% if @user.avatar? %>
      <%= image_tag @user.avatar_url, class: 'icon' %>
    <% else %>
      <%= image_tag ("knife_and_folk.png"), size: "100x100", class: 'icon' %>
    <% end %>
    </div>
    <div class="user-info">
      <h3><%= @user.name %></h3>
      <p><%= @user.profile %></p>
    </div>
  </div>
</div>
<div class="edit-btn">
  <% if current_user.id == @user.id %>
    <%= link_to edit_user_registration_path do %>
      <p>プロフィールを編集<i class="fas fa-edit"></i></p>
    <% end %>
  <% end %>
  <a class="link" href="/users/edit" ></a>
</div>
</div>
<p id="userpost"></p>
<div class="user-post-meals">
<h2>投稿した料理</h2>
<% @user.meals.order("id DESC").each do |usm| %>
  <div class="meals-container">
  <div class="meal">
    <% if user_signed_in? && current_user.id == usm.user_id %>
      <i class="fas fa-feather"></i>
    <% end %>
    <p class="mealname"><%= usm.name %></p>
    <% if usm.image? %>
        <%= image_tag usm.image_url, size: "250x200" %>
    <% else %>
        <%= image_tag ("no_image.png"), size: "250x200" %>
    <% end %>
    <p class="time">
      <p>作成日: <%= usm.created_at.to_s(:datetime_jp) %></p>
      <p>更新日: <%= usm.updated_at.to_s(:datetime_jp) %></p>
    </p>
    <a class="link" href="/meals/<%= usm.id %>" >
    <div class="mask">
        <div class="caption">
          <%= image_tag ("to_show.png"),  width: '100%', height: '100%' %>
        </div>
    </div>
    </a>
  </div>
  <div class="post-sidemenu">
    <div class="like">
      <% if user_signed_in? %>
          <% if current_user.already_liked?(usm) %>
              <%= link_to meal_like_path(id: usm.id, meal_id: usm.id), method: :delete do %>
                  <i class="fas fa-heart fa-lg"></i><span><%= usm.likes.count %></span>
              <% end %>
          <% else %>
              <%= link_to meal_likes_path(id: usm.id, meal_id: usm.id), method: :post do %>
                  <i class="far fa-heart fa-lg"></i><span><%= usm.likes.count %></span>
              <% end %>
          <% end %>
      <% else %>
          <i class="far fa-heart fa-lg"></i><span><%= usm.likes.count %></span>
      <% end %>
    </div>
    <div class="edit-icon">
      <%= link_to edit_meal_path(usm.id) do %>
        <p><span><i class="fas fa-edit fa-lg"></i>編集</span></p>
      <% end %>
    </div>
    <div class="delete-icon">
      <%= link_to meal_path(usm.id), method: :delete, data: {confirm: "削除しますか？"} do %>
        <p><span><i class="fas fa-trash-alt fa-lg"></i>削除</span></p>
      <% end %>
    </div>
  </div>
  </div>
  <% end %>
</div>
<p id="userlike"></p>
<div class="user-like-meals">
<h2>いいねした料理</h2>
<% @user.liked_meals.each do |like| %>
  <div class="meals-container">
  <div class="meal">
    <% if user_signed_in? && current_user.id == like.user_id %>
      <i class="fas fa-feather"></i>
    <% end %>
    <p class="mealname"><%= like.name %></p>
    <% if like.image? %>
        <%= image_tag like.image_url, size: "250x200" %>
    <% else %>
        <%= image_tag ("no_image.png"), size: "250x200" %>
    <% end %>
    <p class="time">
      <p>作成日: <%= like.created_at.to_s(:datetime_jp) %></p>
      <p>更新日: <%= like.updated_at.to_s(:datetime_jp) %></p>
    </p>
    <a class="link" href="/meals/<%= like.id %>" >
    <div class="mask">
        <div class="caption">
          <%= image_tag ("to_show.png"),  width: '100%', height: '100%' %>
        </div>
    </div>
    </a>
  </div>
  <div class="like">
    <% if user_signed_in? %>
        <% if current_user.already_liked?(like) %>
            <%= link_to meal_like_path(id: like.id, meal_id: like.id), method: :delete do %>
                <i class="fas fa-heart fa-lg"></i><span><%= like.likes.count %></span>
            <% end %>
        <% else %>
            <%= link_to meal_likes_path(id: like.id, meal_id: like.id), method: :post do %>
                <i class="far fa-heart fa-lg"></i><span><%= like.likes.count %></span>
            <% end %>
        <% end %>
    <% else %>
        <i class="far fa-heart fa-lg"></i><span><%= like.likes.count %></span>
    <% end %>
  </div>
  </div>
<% end %>
</div>
<p id="usercomment"></p>
<div class="comment-wrapper">
<h2>コメントした料理</h2>
<% @user.comments.each do |c| %>
  <div class="comment">
    <div class="comment-content">
      <p><%= c.content %><p>
      <p class="time">
        <%= c.created_at.to_s(:datetime_jp) %>
      </p>
    </div>
    <%= link_to meal_path(c.meal.id) do %>
      <div class="do_comment_meal">
      <p class="mealname"><%= c.meal.name %></p>
      <% if c.meal.image? %>
          <%= image_tag c.meal.image_url, size: "125x100" %>
      <% else %>
          <%= image_tag ("no_image.png"), size: "125x100" %>
      <% end %>
      <a class="link" href="/meals/<%= c.meal.id %>" ></a>
      </div>
    <% end %>
  </div>
<% end %>
</div>

</body>
</html>